import { Injectable, inject } from '@angular/core';
import { KittyConfigAST } from '../models/kitty-types';
import { DEFAULT_KITTY_CONFIG } from '../models/kitty-defaults';
import { KittyVersionService } from './kitty-version.service';

const MULTILINE_KEYS = new Set([
  'symbol_map', 'narrow_symbols', 'font_features', 'modify_font',
  'watcher', 'exe_search_path', 'menu_map', 'remote_control_password',
  'transparent_background_colors', 'action_alias',
]);

const COMMA_SEPARATED_KEYS = new Set([
  'enabled_layouts', 'paste_actions',
]);

const SPACE_SEPARATED_KEYS = new Set([
  'box_drawing_scale', 'tab_fade', 'tab_bar_margin_height',
  'cursor_trail_decay', 'url_prefixes', 'clipboard_control',
  'clone_source_strategies', 'file_transfer_confirmation_bypass',
]);

// Keys that require quoted values when they have leading/trailing spaces
const QUOTED_STRING_KEYS = new Set([
  'tab_activity_symbol', 'tab_separator', 'bell_on_tab', 'tab_title_template',
  'active_tab_title_template',
]);

// Keys with special boolean handling (not standard yes/no)
const SPECIAL_BOOLEAN_KEYS = new Set<string>([]);

@Injectable({
  providedIn: 'root'
})
export class KittyGeneratorService {
  private readonly versionService = inject(KittyVersionService);

  generateConfig(config: KittyConfigAST): string {
    const now = new Date().toISOString().slice(0, 10);
    let output = `# kitty.conf - Generated by Confitty (${now})\n`;
    output += '# Place this file at: ~/.config/kitty/kitty.conf\n';
    output += '# Reload without restart: Ctrl+Shift+F5  |  Docs: https://sw.kovidgoyal.net/kitty/conf/\n';
    output += '# Only settings that differ from Kitty defaults are included.\n\n';

    output += this.generateSection('Fonts', config.fonts as unknown as Record<string, unknown>, DEFAULT_KITTY_CONFIG.fonts as unknown as Record<string, unknown>);
    output += this.generateSection('Cursor', config.cursor as unknown as Record<string, unknown>, DEFAULT_KITTY_CONFIG.cursor as unknown as Record<string, unknown>);
    output += this.generateSection('Scrollback', config.scrollback as unknown as Record<string, unknown>, DEFAULT_KITTY_CONFIG.scrollback as unknown as Record<string, unknown>);
    output += this.generateSection('Mouse', config.mouse as unknown as Record<string, unknown>, DEFAULT_KITTY_CONFIG.mouse as unknown as Record<string, unknown>);
    output += this.generateSection('Performance', config.performance as unknown as Record<string, unknown>, DEFAULT_KITTY_CONFIG.performance as unknown as Record<string, unknown>);
    output += this.generateSection('Bell', config.bell as unknown as Record<string, unknown>, DEFAULT_KITTY_CONFIG.bell as unknown as Record<string, unknown>);
    output += this.generateSection('Window Layout', config.window_layout as unknown as Record<string, unknown>, DEFAULT_KITTY_CONFIG.window_layout as unknown as Record<string, unknown>);
    output += this.generateSection('Tab Bar', config.tab_bar as unknown as Record<string, unknown>, DEFAULT_KITTY_CONFIG.tab_bar as unknown as Record<string, unknown>);
    output += this.generateSection('Colors', config.colors as unknown as Record<string, unknown>, DEFAULT_KITTY_CONFIG.colors as unknown as Record<string, unknown>);
    output += this.generateAdvancedSection(config);
    output += this.generateSection('OS Specific', config.os_specific as unknown as Record<string, unknown>, DEFAULT_KITTY_CONFIG.os_specific as unknown as Record<string, unknown>);

    if (config.keyboard_shortcuts.length > 0 || config.kitty_mod !== DEFAULT_KITTY_CONFIG.kitty_mod) {
      output += '# --- Keyboard Shortcuts ---\n';
      
      if (config.kitty_mod !== DEFAULT_KITTY_CONFIG.kitty_mod) {
        output += `kitty_mod ${config.kitty_mod}\n`;
      }
      
      for (const mapping of config.keyboard_shortcuts) {
        output += `map ${mapping.chord} ${mapping.action}\n`;
      }
      output += '\n';
    }

    if (config.mouse_mappings.length > 0) {
      output += '# --- Mouse Mappings ---\n';
      for (const mapping of config.mouse_mappings) {
        output += `mouse_map ${mapping.button} ${mapping.event} ${mapping.modes} ${mapping.action}\n`;
      }
      output += '\n';
    }

    if (config.unrecognized_directives.length > 0) {
      output += '# --- Custom Directives ---\n';
      for (const directive of config.unrecognized_directives) {
        output += `${directive}\n`;
      }
      output += '\n';
    }

    return output;
  }

  private generateAdvancedSection(config: KittyConfigAST): string {
    const advanced = config.advanced as unknown as Record<string, unknown>;
    const defaults = DEFAULT_KITTY_CONFIG.advanced as unknown as Record<string, unknown>;
    const lines: string[] = [];

    for (const key in advanced) {
      if (!Object.hasOwn(advanced, key)) continue;

      if (key === 'env') {
        this.collectEnvLines(advanced, defaults, lines);
        continue;
      }

      this.collectConfigLine(key, advanced[key], defaults[key], lines);
    }

    return this.formatSection('Advanced', lines);
  }

  private collectEnvLines(
    advanced: Record<string, unknown>,
    defaults: Record<string, unknown>,
    lines: string[]
  ): void {
    const envRecord = advanced['env'] as Record<string, string>;
    const defaultEnvRecord = defaults['env'] as Record<string, string>;
    const envReadFromShell = advanced['env_read_from_shell'] as boolean;
    const defaultEnvReadFromShell = defaults['env_read_from_shell'] as boolean;
    
    // Handle env read_from_shell directive
    if (envReadFromShell !== defaultEnvReadFromShell && envReadFromShell) {
      lines.push('env read_from_shell');
    }
    
    for (const envKey in envRecord) {
      if (!Object.hasOwn(envRecord, envKey)) continue;
      const val = envRecord[envKey];
      const defaultVal = defaultEnvRecord[envKey];
      if (val !== defaultVal) {
        lines.push(`env ${envKey}=${val}`);
      }
    }
  }

  private collectConfigLine(
    key: string,
    currentValue: unknown,
    defaultValue: unknown,
    lines: string[]
  ): void {
    if (!this.isDifferent(currentValue, defaultValue)) return;

    const formatted = this.formatValueForKey(key, currentValue);
    if (formatted !== null) {
      lines.push(...formatted);
    }
  }

  private formatSection(title: string, lines: string[]): string {
    if (lines.length === 0) return '';
    
    let section = `# --- ${title} ---\n`;
    for (const line of lines) {
      section += `${line}\n`;
    }
    return section + '\n';
  }

  private generateSection(title: string, current: Record<string, unknown>, defaults: Record<string, unknown>): string {
    const lines: string[] = [];

    for (const key in current) {
      if (!Object.hasOwn(current, key)) continue;
      this.processSectionKey(key, current, defaults, lines);
    }

    return this.formatSection(title, lines);
  }

  private processSectionKey(
    key: string,
    current: Record<string, unknown>,
    defaults: Record<string, unknown>,
    lines: string[]
  ): void {
    // Handle options not available in current Kitty version
    if (!this.versionService.isOptionAvailable(key)) {
      this.collectUnavailableOption(key, current, defaults, lines);
      return;
    }

    // Handle confirm_os_window_close with count-background suffix
    if (key === 'confirm_os_window_close') {
      const currentVal = current['confirm_os_window_close'] as number;
      const defaultVal = defaults['confirm_os_window_close'] as number;
      const countBg = current['confirm_os_window_close_count_background'] as boolean;
      const defaultCountBg = defaults['confirm_os_window_close_count_background'] as boolean;
      if (currentVal !== defaultVal || countBg !== defaultCountBg) {
        this.collectConfirmWindowClose(current, lines);
      }
      return;
    }

    this.collectConfigLine(key, current[key], defaults[key], lines);
  }

  private collectUnavailableOption(
    key: string,
    current: Record<string, unknown>,
    defaults: Record<string, unknown>,
    lines: string[]
  ): void {
    const requirement = this.versionService.getVersionRequirement(key);
    if (!requirement || !this.isDifferent(current[key], defaults[key])) return;

    const formatted = this.formatValueForKey(key, current[key]);
    if (formatted) {
      lines.push(`# ${formatted[0]}  # Requires Kitty >= ${requirement.minVersion}`);
    }
  }

  private collectConfirmWindowClose(current: Record<string, unknown>, lines: string[]): void {
    const numValue = current['confirm_os_window_close'] as number;
    const countBackground = current['confirm_os_window_close_count_background'] as boolean;
    const suffix = countBackground ? ' count-background' : '';
    lines.push(`confirm_os_window_close ${numValue}${suffix}`);
  }

  private formatValue(value: unknown): string {
    if (value == null) return '';
    if (Array.isArray(value)) return JSON.stringify(value);
    if (typeof value === 'object') return JSON.stringify(value);
    if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
      return String(value);
    }
    return '';
  }

  private formatValueForKey(key: string, value: unknown): string[] | null {
    if (value === null || value === undefined) return null;

    if (Array.isArray(value)) {
      return this.formatArrayValue(key, value);
    }

    if (typeof value === 'boolean') {
      return [`${key} ${value ? 'yes' : 'no'}`];
    }

    if (typeof value === 'string') {
      return this.formatStringValue(key, value);
    }

    if (typeof value === 'object') {
      return [`${key} ${this.formatValue(value)}`];
    }

    return [`${key} ${this.formatValue(value)}`];
  }

  private formatArrayValue(key: string, value: unknown[]): string[] | null {
    if (value.length === 0) return null;

    if (MULTILINE_KEYS.has(key)) {
      return value.map(entry => `${key} ${this.formatValue(entry)}`);
    }

    if (COMMA_SEPARATED_KEYS.has(key)) {
      return [`${key} ${value.map(v => this.formatValue(v)).join(',')}`];
    }

    return [`${key} ${value.map(v => this.formatValue(v)).join(' ')}`];
  }

  private formatStringValue(key: string, value: string): string[] {
    const needsQuoting = QUOTED_STRING_KEYS.has(key) && (/^\s|\s$/.test(value) || value.includes('#'));
    const formattedValue = needsQuoting ? `"${value}"` : value;
    return [`${key} ${formattedValue}`];
  }

  private isDifferent(a: unknown, b: unknown): boolean {
    if (Array.isArray(a) && Array.isArray(b)) {
      return JSON.stringify(a) !== JSON.stringify(b);
    }

    if (typeof a === 'object' && typeof b === 'object' && a !== null && b !== null) {
      return JSON.stringify(a) !== JSON.stringify(b);
    }

    return a !== b;
  }

  downloadConfig(config: KittyConfigAST, filename: string = 'kitty.conf'): void {
    const configText = this.generateConfig(config);
    const blob = new Blob([configText], { type: 'text/plain' });
    const url = globalThis.URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    link.remove();
    globalThis.URL.revokeObjectURL(url);
  }
}
