import { Injectable } from '@angular/core';

export interface ConfigPreset {
  id: string;
  name: string;
  description: string;
  category: 'theme' | 'performance' | 'minimal' | 'feature-rich' | 'gaming';
  author?: string;
  tags?: string[];
  config: Partial<Record<string, string | number | boolean | string[] | number[]>>;
}

@Injectable({
  providedIn: 'root'
})
export class PresetsService {
  private readonly presets: ConfigPreset[] = [
    {
      id: 'confitty',
      name: 'Confitty',
      description: 'Official Confitty theme. Playful pastel palette inspired by our mascot — soft pinks and confetti accents meet terminal charcoal for a delightful coding experience.',
      category: 'theme',
      author: 'Confitty',
      tags: ['official', 'pastel', 'cat', 'confitty'],
      config: {
        foreground: '#FFFFFF',
        background: '#564D50',
        cursor: '#FFB5C6',
        cursor_text_color: '#564D50',
        selection_foreground: '#564D50',
        selection_background: '#FFB5C6',
        color0: '#564D50',
        color1: '#FE8AEC',
        color2: '#76D36E',
        color3: '#FAF089',
        color4: '#9DC3CA',
        color5: '#C1A3C4',
        color6: '#B2DAB3',
        color7: '#FFFFFF',
        color8: '#6B6164',
        color9: '#FF9DED',
        color10: '#8EE486',
        color11: '#FBF59D',
        color12: '#B0D4DA',
        color13: '#D4B8D7',
        color14: '#C2E4C3',
        color15: '#F0F0F0',
        mark1_foreground: '#564D50',
        mark1_background: '#FFB5C6',
        mark2_foreground: '#564D50',
        mark2_background: '#76D36E',
        mark3_foreground: '#564D50',
        mark3_background: '#9DC3CA',
        cursor_shape: 'beam',
        cursor_blink_interval: 0.5,
        cursor_beam_thickness: 1.8,
        cursor_trail: 3,
        cursor_trail_decay: [0.1, 0.35],
        cursor_trail_start_threshold: 2,
        font_size: 12,
        font_family: 'JetBrains Mono',
        disable_ligatures: 'cursor',
        modify_font: 'cell_height=120%',
        scrollback_lines: 15000,
        wheel_scroll_multiplier: 5,
        touch_scroll_multiplier: 1.5,
        mouse_hide_wait: 3,
        detect_urls: true,
        url_style: 'curly',
        url_color: '#9DC3CA',
        url_prefixes: ['http', 'https', 'ftp', 'file', 'mailto'],
        open_url_with: 'default',
        copy_on_select: 'clipboard',
        paste_actions: ['quote-urls-at-prompt', 'replace-dangerous-control-codes'],
        strip_trailing_spaces: 'smart',
        select_by_word_characters: '@-./_~?&=%+#',
        click_interval: 0.5,
        focus_follows_mouse: false,
        pointer_shape_when_grabbed: 'arrow',
        default_pointer_shape: 'beam',
        pointer_shape_when_dragging: 'beam',
        url_excluded_characters: '',
        clear_selection_on_clipboard_loss: false,
        tab_bar_edge: 'top',
        tab_bar_style: 'powerline',
        tab_powerline_style: 'slanted',
        tab_bar_min_tabs: 2,
        tab_bar_align: 'left',
        tab_fade: [0.25, 0.5, 0.75, 1],
        tab_separator: ' |',
        tab_title_max_length: 25,
        active_tab_foreground: '#564D50',
        active_tab_background: '#FFB5C6',
        inactive_tab_foreground: '#FFFFFF',
        inactive_tab_background: '#6B6164',
        active_tab_font_style: 'bold',
        inactive_tab_font_style: 'normal',
        tab_bar_background: '#564D50',
        window_padding_width: 12,
        window_margin_width: 0,
        window_border_width: '1pt',
        draw_minimal_borders: true,
        active_border_color: '#FFB5C6',
        inactive_border_color: '#6B6164',
        bell_border_color: '#FE8AEC',
        inactive_text_alpha: 0.7,
        background_opacity: 0.97,
        background_blur: 16,
        dim_opacity: 0.75,
        background_tint: 0,
        enable_audio_bell: false,
        visual_bell_duration: 0.2,
        visual_bell_color: '#FFB5C6',
        window_alert_on_bell: true,
        bell_on_tab: '🔔',
        repaint_delay: 10,
        input_delay: 3,
        sync_to_monitor: true,
        remember_window_size: true,
        confirm_os_window_close: 1,
        resize_debounce_time: 0.1,
        resize_in_steps: false,
        initial_window_width: 100,
        initial_window_height: 30,
        placement_strategy: 'center',
        hide_window_decorations: false,
        allow_remote_control: 'socket-only',
        shell_integration: 'enabled',
        update_check_interval: 24,
        wayland_titlebar_color: '#564D50',
        macos_titlebar_color: '#564D50',
      }
    },
    {
      id: 'dracula',
      name: 'Dracula',
      description: 'Popular dark theme with vibrant accents. Excellent contrast and readability for long coding sessions.',
      category: 'theme',
      author: 'Dracula Theme',
      tags: ['dark', 'vibrant', 'popular'],
      config: {
        foreground: '#f8f8f2',
        background: '#282a36',
        cursor: '#f8f8f2',
        cursor_text_color: '#282a36',
        selection_foreground: '#ffffff',
        selection_background: '#44475a',
        color0: '#21222c', color1: '#ff5555', color2: '#50fa7b', color3: '#f1fa8c',
        color4: '#bd93f9', color5: '#ff79c6', color6: '#8be9fd', color7: '#f8f8f2',
        color8: '#6272a4', color9: '#ff6e6e', color10: '#69ff94', color11: '#ffffa5',
        color12: '#d6acff', color13: '#ff92df', color14: '#a4ffff', color15: '#ffffff',
        cursor_shape: 'block', cursor_blink_interval: 0.5, cursor_trail: 3, cursor_trail_decay: [0.1, 0.4], cursor_trail_start_threshold: 2,
        font_size: 12, font_family: 'FiraCode Nerd Font', disable_ligatures: 'cursor',
        scrollback_lines: 10000, wheel_scroll_multiplier: 5,
        detect_urls: true, url_style: 'curly', url_color: '#8be9fd',
        copy_on_select: 'clipboard', strip_trailing_spaces: 'smart',
        tab_bar_style: 'powerline', tab_powerline_style: 'slanted', tab_bar_edge: 'top', tab_bar_min_tabs: 2,
        active_tab_foreground: '#282a36', active_tab_background: '#bd93f9',
        inactive_tab_foreground: '#f8f8f2', inactive_tab_background: '#44475a',
        tab_bar_background: '#21222c',
        active_border_color: '#bd93f9', inactive_border_color: '#6272a4', bell_border_color: '#ff5555',
        window_padding_width: 8, window_border_width: '1pt', draw_minimal_borders: true,
        inactive_text_alpha: 0.7, background_opacity: 0.95, background_blur: 20, dim_opacity: 0.75,
        enable_audio_bell: false, visual_bell_duration: 0.1, window_alert_on_bell: true,
        repaint_delay: 10, input_delay: 3, sync_to_monitor: true,
        remember_window_size: true, confirm_os_window_close: 1,
      }
    },
    {
      id: 'nord',
      name: 'Nord',
      description: 'Arctic, north-bluish palette. Cool muted tones and elegant design perfect for focused developers.',
      category: 'theme',
      author: 'Nord Theme',
      tags: ['dark', 'blue', 'elegant'],
      config: {
        foreground: '#d8dee9', background: '#2e3440', cursor: '#d8dee9',
        selection_foreground: '#2e3440', selection_background: '#88c0d0',
        color0: '#3b4252', color1: '#bf616a', color2: '#a3be8c', color3: '#ebcb8b',
        color4: '#81a1c1', color5: '#b48ead', color6: '#88c0d0', color7: '#e5e9f0',
        color8: '#4c566a', color9: '#bf616a', color10: '#a3be8c', color11: '#ebcb8b',
        color12: '#81a1c1', color13: '#b48ead', color14: '#8fbcbb', color15: '#eceff4',
        cursor_shape: 'beam', cursor_blink_interval: 0.5, cursor_beam_thickness: 1.5, cursor_trail: 2, cursor_trail_decay: [0.15, 0.4], cursor_trail_start_threshold: 2,
        font_size: 11, font_family: 'JetBrains Mono', disable_ligatures: 'cursor',
        scrollback_lines: 10000, wheel_scroll_multiplier: 5,
        detect_urls: true, url_style: 'curly', url_color: '#88c0d0',
        copy_on_select: 'clipboard', strip_trailing_spaces: 'smart',
        tab_bar_style: 'fade', tab_bar_edge: 'bottom', tab_bar_min_tabs: 2,
        active_tab_foreground: '#2e3440', active_tab_background: '#88c0d0',
        inactive_tab_foreground: '#d8dee9', inactive_tab_background: '#3b4252',
        tab_bar_background: '#2e3440',
        active_border_color: '#88c0d0', inactive_border_color: '#4c566a', bell_border_color: '#bf616a',
        window_padding_width: 8, window_border_width: '1pt', draw_minimal_borders: true,
        inactive_text_alpha: 0.7, background_opacity: 0.98, background_blur: 16, dim_opacity: 0.75,
        enable_audio_bell: false, window_alert_on_bell: true,
        repaint_delay: 10, input_delay: 3, sync_to_monitor: true,
        remember_window_size: true, confirm_os_window_close: 1,
      }
    },
    {
      id: 'gruvbox-dark',
      name: 'Gruvbox Dark',
      description: 'Retro groove with warm earthy tones. Easy on the eyes for marathon coding sessions.',
      category: 'theme',
      author: 'Gruvbox',
      tags: ['dark', 'warm', 'retro'],
      config: {
        foreground: '#ebdbb2', background: '#282828', cursor: '#ebdbb2',
        selection_foreground: '#282828', selection_background: '#ebdbb2',
        color0: '#282828', color1: '#cc241d', color2: '#98971a', color3: '#d79921',
        color4: '#458588', color5: '#b16286', color6: '#689d6a', color7: '#a89984',
        color8: '#928374', color9: '#fb4934', color10: '#b8bb26', color11: '#fabd2f',
        color12: '#83a598', color13: '#d3869b', color14: '#8ec07c', color15: '#ebdbb2',
        cursor_shape: 'block', cursor_blink_interval: 0, cursor_trail: 2, cursor_trail_decay: [0.2, 0.45], cursor_trail_start_threshold: 2,
        font_size: 11, font_family: 'Source Code Pro', disable_ligatures: 'cursor',
        scrollback_lines: 10000, wheel_scroll_multiplier: 5,
        detect_urls: true, url_style: 'curly', url_color: '#83a598',
        copy_on_select: 'clipboard', strip_trailing_spaces: 'smart',
        tab_bar_style: 'separator', tab_separator: ' ┇', tab_bar_edge: 'bottom', tab_bar_min_tabs: 2,
        active_tab_foreground: '#282828', active_tab_background: '#fabd2f',
        inactive_tab_foreground: '#ebdbb2', inactive_tab_background: '#3c3836',
        tab_bar_background: '#282828',
        active_border_color: '#fabd2f', inactive_border_color: '#504945', bell_border_color: '#fb4934',
        window_padding_width: 10, window_border_width: '1pt', draw_minimal_borders: true,
        inactive_text_alpha: 0.75, background_opacity: 1, dim_opacity: 0.75,
        enable_audio_bell: false, window_alert_on_bell: true,
        repaint_delay: 10, input_delay: 3, sync_to_monitor: true,
        remember_window_size: true, confirm_os_window_close: 1,
      }
    },
    {
      id: 'tokyo-night',
      name: 'Tokyo Night',
      description: 'Inspired by Tokyo city lights. A perfect blend of aesthetics and functionality for extended use.',
      category: 'theme',
      author: 'Tokyo Night',
      tags: ['dark', 'blue', 'modern'],
      config: {
        foreground: '#a9b1d6', background: '#1a1b26', cursor: '#c0caf5',
        cursor_text_color: '#1a1b26', selection_foreground: '#1a1b26', selection_background: '#7aa2f7',
        color0: '#15161e', color1: '#f7768e', color2: '#9ece6a', color3: '#e0af68',
        color4: '#7aa2f7', color5: '#bb9af7', color6: '#7dcfff', color7: '#a9b1d6',
        color8: '#414868', color9: '#f7768e', color10: '#9ece6a', color11: '#e0af68',
        color12: '#7aa2f7', color13: '#bb9af7', color14: '#7dcfff', color15: '#c0caf5',
        cursor_shape: 'beam', cursor_blink_interval: 0.5, cursor_beam_thickness: 1.5, cursor_trail: 4, cursor_trail_decay: [0.15, 0.45], cursor_trail_start_threshold: 2,
        font_size: 12, font_family: 'Cascadia Code', disable_ligatures: 'never',
        scrollback_lines: 15000, wheel_scroll_multiplier: 5,
        detect_urls: true, url_style: 'curly', url_color: '#7aa2f7',
        copy_on_select: 'clipboard', strip_trailing_spaces: 'smart',
        tab_bar_style: 'powerline', tab_powerline_style: 'angled', tab_bar_edge: 'top', tab_bar_min_tabs: 2,
        active_tab_foreground: '#1a1b26', active_tab_background: '#7aa2f7',
        inactive_tab_foreground: '#a9b1d6', inactive_tab_background: '#16161e',
        tab_bar_background: '#15161e',
        active_border_color: '#7aa2f7', inactive_border_color: '#414868', bell_border_color: '#f7768e',
        window_padding_width: 8, window_border_width: '1pt', draw_minimal_borders: true,
        inactive_text_alpha: 0.7, background_opacity: 0.95, background_blur: 32, dim_opacity: 0.75,
        enable_audio_bell: false, window_alert_on_bell: true,
        repaint_delay: 10, input_delay: 3, sync_to_monitor: true,
        remember_window_size: true, confirm_os_window_close: 1,
      }
    },
    {
      id: 'catppuccin-mocha',
      name: 'Catppuccin Mocha',
      description: 'Soothing pastel theme for long coding sessions. Soft colors that dramatically reduce eye strain.',
      category: 'theme',
      author: 'Catppuccin',
      tags: ['dark', 'pastel', 'soft'],
      config: {
        foreground: '#cdd6f4', background: '#1e1e2e', cursor: '#f5e0dc',
        selection_foreground: '#1e1e2e', selection_background: '#f5c2e7',
        color0: '#45475a', color1: '#f38ba8', color2: '#a6e3a1', color3: '#f9e2af',
        color4: '#89b4fa', color5: '#f5c2e7', color6: '#94e2d5', color7: '#bac2de',
        color8: '#585b70', color9: '#f38ba8', color10: '#a6e3a1', color11: '#f9e2af',
        color12: '#89b4fa', color13: '#f5c2e7', color14: '#94e2d5', color15: '#a6adc8',
        cursor_shape: 'beam', cursor_blink_interval: 0.5, cursor_beam_thickness: 1.5, cursor_trail: 3, cursor_trail_decay: [0.1, 0.35], cursor_trail_start_threshold: 2,
        font_size: 11, font_family: 'Iosevka', disable_ligatures: 'cursor',
        scrollback_lines: 10000, wheel_scroll_multiplier: 5,
        detect_urls: true, url_style: 'curly', url_color: '#89b4fa',
        copy_on_select: 'clipboard', strip_trailing_spaces: 'smart',
        tab_bar_style: 'fade', tab_bar_edge: 'top', tab_bar_min_tabs: 2,
        active_tab_foreground: '#1e1e2e', active_tab_background: '#f5c2e7',
        inactive_tab_foreground: '#cdd6f4', inactive_tab_background: '#313244',
        tab_bar_background: '#1e1e2e',
        active_border_color: '#f5c2e7', inactive_border_color: '#6c7086', bell_border_color: '#f38ba8',
        window_padding_width: 12, window_border_width: '1pt', draw_minimal_borders: true,
        inactive_text_alpha: 0.7, background_opacity: 0.95, background_blur: 20, dim_opacity: 0.75,
        enable_audio_bell: false, window_alert_on_bell: true,
        repaint_delay: 10, input_delay: 3, sync_to_monitor: true,
        remember_window_size: true, confirm_os_window_close: 1,
      }
    },
    {
      id: 'everforest-dark',
      name: 'Everforest Dark',
      description: 'Warm forest-inspired color scheme. Natural green and earthy tones for a comfortable workspace.',
      category: 'theme',
      author: 'sainnhe',
      tags: ['dark', 'green', 'warm'],
      config: {
        foreground: '#d3c6aa', background: '#2d353b', cursor: '#d3c6aa',
        cursor_text_color: '#2d353b', selection_foreground: '#2d353b', selection_background: '#a7c080',
        color0: '#475258', color1: '#e67e80', color2: '#a7c080', color3: '#dbbc7f',
        color4: '#7fbbb3', color5: '#d699b6', color6: '#83c092', color7: '#d3c6aa',
        color8: '#475258', color9: '#e67e80', color10: '#a7c080', color11: '#dbbc7f',
        color12: '#7fbbb3', color13: '#d699b6', color14: '#83c092', color15: '#d3c6aa',
        cursor_shape: 'block', cursor_blink_interval: 0.5, cursor_trail: 3, cursor_trail_decay: [0.1, 0.35], cursor_trail_start_threshold: 2,
        font_size: 12, font_family: 'JetBrains Mono', disable_ligatures: 'cursor',
        scrollback_lines: 10000, wheel_scroll_multiplier: 5,
        detect_urls: true, url_style: 'curly', url_color: '#7fbbb3',
        copy_on_select: 'clipboard', strip_trailing_spaces: 'smart',
        tab_bar_style: 'fade', tab_bar_edge: 'bottom', tab_bar_min_tabs: 2,
        active_tab_foreground: '#2d353b', active_tab_background: '#a7c080',
        inactive_tab_foreground: '#d3c6aa', inactive_tab_background: '#3d4841',
        active_border_color: '#a7c080', inactive_border_color: '#475258', bell_border_color: '#e67e80',
        window_padding_width: 10, window_border_width: '1pt', draw_minimal_borders: true,
        inactive_text_alpha: 0.75, background_opacity: 0.97, dim_opacity: 0.75,
        enable_audio_bell: false, window_alert_on_bell: true,
        repaint_delay: 10, input_delay: 3, sync_to_monitor: true,
        remember_window_size: true, confirm_os_window_close: 1,
      }
    },
    {
      id: 'kanagawa-wave',
      name: 'Kanagawa Wave',
      description: 'Inspired by the Great Wave painting. Deep ocean blues and warm amber accents for a serene workspace.',
      category: 'theme',
      author: 'rebelot',
      tags: ['dark', 'blue', 'calm'],
      config: {
        foreground: '#dcd7ba', background: '#1f1f28', cursor: '#c8c093',
        cursor_text_color: '#1f1f28', selection_foreground: '#1f1f28', selection_background: '#2d4f67',
        color0: '#16161d', color1: '#c34043', color2: '#76946a', color3: '#c0a36e',
        color4: '#7e9cd8', color5: '#957fb8', color6: '#6a9589', color7: '#c8c093',
        color8: '#727169', color9: '#ff5d62', color10: '#98bb6c', color11: '#e6c384',
        color12: '#7fb4ca', color13: '#938aa9', color14: '#7aa89f', color15: '#dcd7ba',
        cursor_shape: 'block', cursor_blink_interval: 0, cursor_trail: 2, cursor_trail_decay: [0.2, 0.5], cursor_trail_start_threshold: 3,
        font_size: 12, font_family: 'Noto Mono', disable_ligatures: 'cursor',
        scrollback_lines: 12000, wheel_scroll_multiplier: 5,
        detect_urls: true, url_style: 'curly', url_color: '#7fb4ca',
        copy_on_select: 'clipboard', strip_trailing_spaces: 'smart',
        tab_bar_style: 'separator', tab_separator: '  ', tab_bar_edge: 'bottom', tab_bar_min_tabs: 2,
        active_tab_foreground: '#1f1f28', active_tab_background: '#7e9cd8',
        inactive_tab_foreground: '#dcd7ba', inactive_tab_background: '#2a2a37',
        tab_bar_background: '#16161d',
        active_border_color: '#7e9cd8', inactive_border_color: '#363646', bell_border_color: '#ff5d62',
        window_padding_width: 10, window_border_width: '1pt', draw_minimal_borders: true,
        inactive_text_alpha: 0.7, background_opacity: 1, dim_opacity: 0.8,
        enable_audio_bell: false, window_alert_on_bell: true,
        repaint_delay: 10, input_delay: 3, sync_to_monitor: true,
        remember_window_size: true, confirm_os_window_close: 1,
      }
    },
    {
      id: 'ayu-dark',
      name: 'Ayu Dark',
      description: 'Clean dark theme with warm amber accents. Minimal, high-contrast, and easy on the eyes.',
      category: 'theme',
      author: 'Ayu',
      tags: ['dark', 'amber', 'minimal'],
      config: {
        foreground: '#b3b1ad', background: '#0a0e14', cursor: '#e6b450',
        cursor_text_color: '#0a0e14', selection_foreground: '#0a0e14', selection_background: '#253340',
        color0: '#01060e', color1: '#ea6c73', color2: '#91b362', color3: '#f9af4f',
        color4: '#53bdfa', color5: '#fae994', color6: '#90e1c6', color7: '#c7c7c7',
        color8: '#686868', color9: '#f07178', color10: '#c2d94c', color11: '#ffb454',
        color12: '#59c2ff', color13: '#ffee99', color14: '#95e6cb', color15: '#ffffff',
        cursor_shape: 'beam', cursor_blink_interval: 0.5, cursor_beam_thickness: 1.5, cursor_trail: 3, cursor_trail_decay: [0.1, 0.4], cursor_trail_start_threshold: 2,
        font_size: 12, font_family: 'JetBrains Mono', disable_ligatures: 'cursor',
        scrollback_lines: 10000, wheel_scroll_multiplier: 5,
        detect_urls: true, url_style: 'curly', url_color: '#59c2ff',
        copy_on_select: 'clipboard', strip_trailing_spaces: 'smart',
        tab_bar_style: 'powerline', tab_powerline_style: 'angled', tab_bar_edge: 'top', tab_bar_min_tabs: 2,
        active_tab_foreground: '#0a0e14', active_tab_background: '#e6b450',
        inactive_tab_foreground: '#b3b1ad', inactive_tab_background: '#131721',
        tab_bar_background: '#01060e',
        active_border_color: '#e6b450', inactive_border_color: '#253340', bell_border_color: '#ea6c73',
        window_padding_width: 8, window_border_width: '1pt', draw_minimal_borders: true,
        inactive_text_alpha: 0.7, background_opacity: 0.97, background_blur: 16, dim_opacity: 0.8,
        enable_audio_bell: false, window_alert_on_bell: true,
        repaint_delay: 10, input_delay: 3, sync_to_monitor: true,
        remember_window_size: true, confirm_os_window_close: 1,
      }
    },
    {
      id: 'monokai-pro',
      name: 'Monokai Pro',
      description: 'Vibrant high-contrast colors. A professional standard used by millions of developers worldwide.',
      category: 'theme',
      author: 'Monokai',
      tags: ['dark', 'vibrant', 'contrast'],
      config: {
        foreground: '#fcfcfa', background: '#2d2a2e', cursor: '#fcfcfa',
        selection_foreground: '#2d2a2e', selection_background: '#ffd866',
        color0: '#2d2a2e', color1: '#ff6188', color2: '#a9dc76', color3: '#ffd866',
        color4: '#fc9867', color5: '#ab9df2', color6: '#78dce8', color7: '#fcfcfa',
        color8: '#727072', color9: '#ff6188', color10: '#a9dc76', color11: '#ffd866',
        color12: '#fc9867', color13: '#ab9df2', color14: '#78dce8', color15: '#fcfcfa',
        cursor_shape: 'block', cursor_blink_interval: 0, cursor_trail: 2, cursor_trail_decay: [0.15, 0.4], cursor_trail_start_threshold: 2,
        font_size: 12, font_family: 'Hack Nerd Font', disable_ligatures: 'cursor',
        scrollback_lines: 10000, wheel_scroll_multiplier: 5,
        detect_urls: true, url_style: 'curly', url_color: '#78dce8',
        copy_on_select: 'clipboard', strip_trailing_spaces: 'smart',
        tab_bar_style: 'slant', tab_bar_edge: 'top', tab_bar_min_tabs: 2,
        active_tab_foreground: '#2d2a2e', active_tab_background: '#ffd866',
        inactive_tab_foreground: '#fcfcfa', inactive_tab_background: '#403e41',
        tab_bar_background: '#2d2a2e',
        active_border_color: '#ffd866', inactive_border_color: '#727072', bell_border_color: '#ff6188',
        window_padding_width: 8, window_border_width: '1pt', draw_minimal_borders: true,
        inactive_text_alpha: 0.7, background_opacity: 1, dim_opacity: 0.75,
        enable_audio_bell: false, window_alert_on_bell: true,
        repaint_delay: 10, input_delay: 3, sync_to_monitor: true,
        remember_window_size: true, confirm_os_window_close: 1,
      }
    },
    {
      id: 'solarized-dark',
      name: 'Solarized Dark',
      description: 'Scientifically designed for reduced eye strain. The original precision color scheme for developers.',
      category: 'theme',
      author: 'Ethan Schoonover',
      tags: ['dark', 'classic', 'scientific'],
      config: {
        foreground: '#839496', background: '#002b36', cursor: '#839496',
        selection_foreground: '#002b36', selection_background: '#839496',
        color0: '#073642', color1: '#dc322f', color2: '#859900', color3: '#b58900',
        color4: '#268bd2', color5: '#d33682', color6: '#2aa198', color7: '#eee8d5',
        color8: '#002b36', color9: '#cb4b16', color10: '#586e75', color11: '#657b83',
        color12: '#839496', color13: '#6c71c4', color14: '#93a1a1', color15: '#fdf6e3',
        cursor_shape: 'block', cursor_blink_interval: 0, cursor_trail: 2, cursor_trail_decay: [0.2, 0.5], cursor_trail_start_threshold: 3,
        font_size: 11, font_family: 'Inconsolata', disable_ligatures: 'never',
        scrollback_lines: 10000, wheel_scroll_multiplier: 5,
        detect_urls: true, url_style: 'straight', url_color: '#268bd2',
        copy_on_select: 'clipboard', strip_trailing_spaces: 'smart',
        tab_bar_style: 'fade', tab_bar_edge: 'bottom', tab_bar_min_tabs: 2,
        active_tab_foreground: '#002b36', active_tab_background: '#268bd2',
        inactive_tab_foreground: '#839496', inactive_tab_background: '#073642',
        tab_bar_background: '#002b36',
        active_border_color: '#268bd2', inactive_border_color: '#586e75', bell_border_color: '#dc322f',
        window_padding_width: 8, window_border_width: '1pt', draw_minimal_borders: true,
        inactive_text_alpha: 0.7, background_opacity: 1, dim_opacity: 0.75,
        enable_audio_bell: false, window_alert_on_bell: true,
        repaint_delay: 10, input_delay: 3, sync_to_monitor: true,
        remember_window_size: true, confirm_os_window_close: 1,
      }
    },
    {
      id: 'one-dark',
      name: 'One Dark',
      description: 'Atom One Dark with smooth colors. Instantly familiar to VS Code users, excellent for all languages.',
      category: 'theme',
      author: 'Atom',
      tags: ['dark', 'smooth', 'popular'],
      config: {
        foreground: '#abb2bf', background: '#282c34', cursor: '#528bff',
        selection_foreground: '#282c34', selection_background: '#3e4451',
        color0: '#282c34', color1: '#e06c75', color2: '#98c379', color3: '#e5c07b',
        color4: '#61afef', color5: '#c678dd', color6: '#56b6c2', color7: '#abb2bf',
        color8: '#5c6370', color9: '#e06c75', color10: '#98c379', color11: '#e5c07b',
        color12: '#61afef', color13: '#c678dd', color14: '#56b6c2', color15: '#ffffff',
        cursor_shape: 'beam', cursor_blink_interval: 0.5, cursor_beam_thickness: 1.5, cursor_trail: 3, cursor_trail_decay: [0.1, 0.4], cursor_trail_start_threshold: 2,
        font_size: 12, font_family: 'Fira Code', disable_ligatures: 'cursor',
        scrollback_lines: 10000, wheel_scroll_multiplier: 5,
        detect_urls: true, url_style: 'curly', url_color: '#61afef',
        copy_on_select: 'clipboard', strip_trailing_spaces: 'smart',
        tab_bar_style: 'powerline', tab_powerline_style: 'round', tab_bar_edge: 'top', tab_bar_min_tabs: 2,
        active_tab_foreground: '#282c34', active_tab_background: '#61afef',
        inactive_tab_foreground: '#abb2bf', inactive_tab_background: '#21252b',
        tab_bar_background: '#282c34',
        active_border_color: '#61afef', inactive_border_color: '#3e4451', bell_border_color: '#e06c75',
        window_padding_width: 8, window_border_width: '1pt', draw_minimal_borders: true,
        inactive_text_alpha: 0.7, background_opacity: 0.96, background_blur: 20, dim_opacity: 0.75,
        enable_audio_bell: false, window_alert_on_bell: true,
        repaint_delay: 10, input_delay: 3, sync_to_monitor: true,
        remember_window_size: true, confirm_os_window_close: 1,
      }
    },
    {
      id: 'light-professional',
      name: 'Light Professional',
      description: 'Clean light theme for bright environments. Excellent readability with Nord-inspired colors.',
      category: 'theme',
      author: 'Custom',
      tags: ['light', 'clean', 'day'],
      config: {
        foreground: '#2e3440', background: '#fafafa', cursor: '#2e3440',
        cursor_text_color: '#fafafa', selection_foreground: '#ffffff', selection_background: '#5e81ac',
        color0: '#3b4252', color1: '#bf616a', color2: '#a3be8c', color3: '#ebcb8b',
        color4: '#5e81ac', color5: '#b48ead', color6: '#88c0d0', color7: '#e5e9f0',
        color8: '#4c566a', color9: '#bf616a', color10: '#a3be8c', color11: '#ebcb8b',
        color12: '#5e81ac', color13: '#b48ead', color14: '#8fbcbb', color15: '#eceff4',
        cursor_shape: 'beam', cursor_blink_interval: 0.5, cursor_beam_thickness: 1.5, cursor_trail: 2, cursor_trail_decay: [0.15, 0.4], cursor_trail_start_threshold: 2,
        font_size: 11, font_family: 'SF Mono', disable_ligatures: 'cursor',
        scrollback_lines: 10000, detect_urls: true, url_style: 'curly', url_color: '#5e81ac',
        copy_on_select: 'clipboard', strip_trailing_spaces: 'smart',
        tab_bar_style: 'fade', tab_bar_edge: 'top', tab_bar_min_tabs: 2,
        active_tab_foreground: '#ffffff', active_tab_background: '#5e81ac',
        inactive_tab_foreground: '#2e3440', inactive_tab_background: '#d8dee9',
        tab_bar_background: '#eceff4',
        active_border_color: '#5e81ac', inactive_border_color: '#d8dee9', bell_border_color: '#bf616a',
        window_padding_width: 8, window_border_width: '1pt', draw_minimal_borders: true,
        inactive_text_alpha: 0.7, background_opacity: 1, dim_opacity: 0.75,
        enable_audio_bell: false, window_alert_on_bell: true,
        repaint_delay: 10, input_delay: 3, sync_to_monitor: true,
        remember_window_size: true, confirm_os_window_close: 1,
      }
    },
    {
      id: 'performance-optimized',
      name: 'Performance Optimized',
      description: 'Maximum speed for resource-constrained systems. Minimal rendering delays and reduced memory usage.',
      category: 'performance',
      tags: ['fast', 'efficient', 'lightweight'],
      config: {
        repaint_delay: 5, input_delay: 1, sync_to_monitor: true,
        scrollback_lines: 5000, scrollback_pager_history_size: 0,
        wheel_scroll_multiplier: 3, cursor_shape: 'block', cursor_blink_interval: 0,
        font_size: 10, font_family: 'monospace', disable_ligatures: 'always',
        background_opacity: 1, background_blur: 0,
        tab_bar_style: 'fade', tab_bar_min_tabs: 2, window_padding_width: 2, window_border_width: '0pt',
        enable_audio_bell: false, confirm_os_window_close: 0,
      }
    },
    {
      id: 'minimal-clean',
      name: 'Minimal & Clean',
      description: 'Distraction-free setup for focused work. No decorations, maximum screen real estate.',
      category: 'minimal',
      tags: ['minimal', 'focused', 'clean'],
      config: {
        hide_window_decorations: true, tab_bar_style: 'hidden',
        window_padding_width: 16, window_border_width: '0pt',
        background_opacity: 1, font_size: 12, font_family: 'JetBrains Mono', disable_ligatures: 'cursor',
        cursor_shape: 'beam', cursor_blink_interval: 0, cursor_beam_thickness: 1.5,
        scrollback_lines: 10000, enable_audio_bell: false, visual_bell_duration: 0,
        remember_window_size: true, confirm_os_window_close: -1, detect_urls: true,
        foreground: '#c0bfbc', background: '#1c1917',
        color0: '#292524', color1: '#f87171', color2: '#86efac', color3: '#fcd34d',
        color4: '#93c5fd', color5: '#c4b5fd', color6: '#67e8f9', color7: '#c0bfbc',
        color8: '#44403c', color9: '#f87171', color10: '#86efac', color11: '#fcd34d',
        color12: '#93c5fd', color13: '#c4b5fd', color14: '#67e8f9', color15: '#fafaf9',
        active_border_color: '#86efac', inactive_border_color: '#44403c',
        inactive_text_alpha: 0.8, draw_minimal_borders: true,
        repaint_delay: 10, input_delay: 3,
      }
    },
    {
      id: 'developer-default',
      name: 'Developer Default',
      description: 'Balanced configuration for development workflows. The recommended starting point for most developers.',
      category: 'feature-rich',
      tags: ['developer', 'balanced', 'recommended'],
      config: {
        font_family: 'JetBrains Mono', font_size: 12, disable_ligatures: 'cursor',
        cursor_shape: 'beam', cursor_blink_interval: 0.5, cursor_beam_thickness: 1.5, cursor_trail: 2, cursor_trail_decay: [0.1, 0.4], cursor_trail_start_threshold: 2,
        scrollback_lines: 10000, mouse_hide_wait: 3,
        detect_urls: true, url_style: 'curly', copy_on_select: 'clipboard', strip_trailing_spaces: 'smart',
        enable_audio_bell: false, window_padding_width: 8, window_border_width: '1pt',
        tab_bar_style: 'fade', tab_bar_edge: 'bottom',
        background_opacity: 0.98, confirm_os_window_close: 1,
        allow_remote_control: 'socket-only', shell_integration: 'enabled',
        repaint_delay: 10, input_delay: 3, sync_to_monitor: true,
      }
    },
    {
      id: 'feature-rich-power',
      name: 'Power User',
      description: 'All productivity features enabled for professional workflows. Maximum configurability out of the box.',
      category: 'feature-rich',
      tags: ['power-user', 'complete', 'productivity'],
      config: {
        scrollback_lines: 20000, scrollback_pager_history_size: 10, wheel_scroll_multiplier: 5,
        enable_audio_bell: false, visual_bell_duration: 0.2, visual_bell_color: '#ff5555',
        window_alert_on_bell: true, cursor_shape: 'block', cursor_trail: 4, cursor_trail_decay: [0.1, 0.3, 0.5], cursor_trail_start_threshold: 2,
        cursor_blink_interval: 0.5, cursor_stop_blinking_after: 15, mouse_hide_wait: 3,
        url_style: 'curly', open_url_with: 'default', detect_urls: true,
        show_hyperlink_targets: true, copy_on_select: 'clipboard', strip_trailing_spaces: 'smart',
        repaint_delay: 10, input_delay: 3, sync_to_monitor: true,
        font_size: 12, font_family: 'Fira Code', disable_ligatures: 'cursor',
        tab_bar_style: 'powerline', tab_powerline_style: 'angled', tab_bar_edge: 'top', tab_bar_min_tabs: 1,
        window_padding_width: 10, window_border_width: '1pt', remember_window_size: true, confirm_os_window_close: 1,
        background_opacity: 0.95, background_blur: 20, allow_remote_control: 'yes', shell_integration: 'enabled',
        draw_minimal_borders: true, inactive_text_alpha: 0.75,
      }
    },
    {
      id: 'gaming-responsive',
      name: 'Gaming & Responsive',
      description: 'Ultra-low latency for gaming and real-time apps. Tuned for absolute maximum responsiveness.',
      category: 'gaming',
      tags: ['gaming', 'fast', 'low-latency'],
      config: {
        repaint_delay: 3, input_delay: 0, sync_to_monitor: true,
        scrollback_lines: 3000, cursor_shape: 'block', cursor_blink_interval: 0,
        font_size: 11, font_family: 'JetBrains Mono', disable_ligatures: 'always',
        foreground: '#e0e0e0', background: '#0a0a0a', cursor: '#00ff00', cursor_text_color: '#0a0a0a',
        color0: '#1a1a1a', color1: '#ff0055', color2: '#00ff00', color3: '#ffaa00',
        color4: '#0066ff', color5: '#ff00ff', color6: '#00ffff', color7: '#e0e0e0',
        color8: '#666666', color9: '#ff3377', color10: '#33ff33', color11: '#ffcc33',
        color12: '#3388ff', color13: '#ff33ff', color14: '#33ffff', color15: '#ffffff',
        background_opacity: 1, background_blur: 0,
        mouse_hide_wait: 1, detect_urls: true, focus_follows_mouse: false,
        enable_audio_bell: false, visual_bell_duration: 0,
        tab_bar_style: 'hidden', window_padding_width: 2,
        window_border_width: '0pt', inactive_text_alpha: 1,
        confirm_os_window_close: 0, remember_window_size: true,
      }
    }
  ];

  getPresets(): ConfigPreset[] {
    return this.presets;
  }

  getPresetsByCategory(category: ConfigPreset['category']): ConfigPreset[] {
    return this.presets.filter(p => p.category === category);
  }

  getPresetById(id: string): ConfigPreset | undefined {
    return this.presets.find(p => p.id === id);
  }

  getCategories(): Array<{id: ConfigPreset['category'], label: string, description: string}> {
    return [
      { id: 'theme', label: 'Color Themes', description: 'Beautiful color schemes' },
      { id: 'minimal', label: 'Minimal', description: 'Clean & distraction-free' },
      { id: 'performance', label: 'Performance', description: 'Speed optimized' },
      { id: 'gaming', label: 'Gaming', description: 'Low-latency & responsive' },
      { id: 'feature-rich', label: 'Power User', description: 'Feature complete' }
    ];
  }
}
