import { SearchableItem } from './search.types';

function items(category: string, categoryLabel: string, entries: Omit<SearchableItem, 'category' | 'categoryLabel'>[]): SearchableItem[] {
  return entries.map(e => ({ ...e, category, categoryLabel }));
}

export const CONFIG_SEARCH_INDEX: SearchableItem[] = [

  ...items('fonts', 'Fonts', [
    { key: 'font_family',              label: 'Font Family',              description: 'Primary font used to render text in the terminal.',                       tags: ['typeface', 'monospace', 'nerd font', 'fira code', 'jetbrains'] },
    { key: 'font_size',                label: 'Font Size',                description: 'Font size in points. Affects all text in the terminal.',                  tags: ['pt', 'text size', 'zoom'] },
    { key: 'bold_font',                label: 'Bold Font',                description: 'Font variant used for bold text.',                                        tags: ['bold', 'weight', 'typeface'] },
    { key: 'italic_font',              label: 'Italic Font',              description: 'Font variant used for italic text.',                                      tags: ['italic', 'oblique', 'typeface'] },
    { key: 'bold_italic_font',         label: 'Bold Italic Font',         description: 'Font variant used when text is both bold and italic.',                   tags: ['bold italic', 'typeface'] },
    { key: 'force_ltr',                label: 'Force Left-to-Right',      description: 'Forces text layout to left-to-right regardless of content direction.',   tags: ['rtl', 'bidi', 'arabic', 'hebrew', 'direction'] },
    { key: 'disable_ligatures',        label: 'Ligatures',                description: 'Controls when font ligatures are rendered: never, always, or at cursor.', tags: ['ligature', 'arrow', 'coding', 'fira code', 'disable'] },
    { key: 'font_features',            label: 'Font Features',            description: 'Enable or disable specific OpenType font features by name.',              tags: ['opentype', 'ot', 'ss01', 'calt', 'feature'] },
    { key: 'symbol_map',               label: 'Symbol Map',               description: 'Map Unicode code point ranges to a specific font for custom symbols.',    tags: ['nerd font', 'powerline', 'icons', 'unicode', 'glyph'] },
    { key: 'narrow_symbols',           label: 'Narrow Symbols',           description: 'Treat specific symbol code points as narrow (single-width) characters.',  tags: ['width', 'unicode', 'symbol', 'glyph'] },
    { key: 'modify_font',              label: 'Modify Font Metrics',      description: 'Adjust font metrics: cell height, baseline, underline position and size.', tags: ['metrics', 'baseline', 'underline', 'cell height', 'adjust'] },
    { key: 'box_drawing_scale',        label: 'Box Drawing Scale',        description: 'Thickness scaling for built-in box drawing characters.',                  tags: ['box drawing', 'border', 'line', 'scale'] },
    { key: 'undercurl_style',          label: 'Undercurl Style',          description: 'Visual style of the undercurl decoration: thick, thin, or very-thin.',    tags: ['wavy underline', 'squiggle', 'spell check', 'decoration'] },
    { key: 'underline_exclusion',      label: 'Underline Exclusion',      description: 'Gap padding when underlines intersect font descenders like y, g, p. 0 disables gaps.', tags: ['underline', 'gap', 'descender', 'padding', 'rendering'] },
    { key: 'text_composition_strategy', label: 'Text Composition Strategy', description: 'How Kitty composites text glyphs: platform default or legacy mode.',   tags: ['compositing', 'rendering', 'antialiasing', 'cleartype'] },
  ]),

  ...items('cursor', 'Cursor', [
    { key: 'cursor',                     label: 'Cursor Color',                description: 'Color of the terminal cursor. Use "none" to take the foreground color.', tags: ['caret', 'cursor color', 'tint'] },
    { key: 'cursor_text_color',          label: 'Cursor Text Color',           description: 'Color of text under the cursor. Only applies to the block cursor shape.', tags: ['caret text', 'invert', 'block cursor'] },
    { key: 'cursor_shape',               label: 'Cursor Shape',                description: 'Shape of the focused cursor: block, beam (I-beam), or underline.',       tags: ['caret shape', 'block', 'beam', 'underline', 'ibeam'] },
    { key: 'cursor_shape_unfocused',     label: 'Unfocused Cursor Shape',      description: 'Cursor shape when the terminal window is not in focus.',                 tags: ['hollow', 'unfocused', 'inactive'] },
    { key: 'cursor_beam_thickness',      label: 'Cursor Beam Thickness',       description: 'Width in points of the beam (I-beam) cursor.',                          tags: ['beam width', 'ibeam', 'caret thickness'] },
    { key: 'cursor_underline_thickness', label: 'Cursor Underline Thickness',  description: 'Thickness of the underline cursor in points.',                          tags: ['underline cursor', 'caret'] },
    { key: 'cursor_blink_interval',      label: 'Cursor Blink Interval',       description: 'Blink rate in seconds. 0 disables blinking. -1 uses system default.',   tags: ['blink', 'blink rate', 'flash', 'cursor animation'] },
    { key: 'cursor_stop_blinking_after', label: 'Stop Blinking After',         description: 'Stop blinking cursor after this many seconds of keyboard inactivity.',  tags: ['blink stop', 'idle', 'inactivity', 'cursor'] },
    { key: 'cursor_trail',               label: 'Cursor Trail Length',         description: 'Number of phantom cursors left during rapid movement for smooth animation. 0 disables.', tags: ['trail', 'animation', 'smooth', 'phantom', 'gpu'] },
    { key: 'cursor_trail_decay',         label: 'Cursor Trail Decay',          description: 'Exponential alpha fade values for cursor trail animation.',              tags: ['trail', 'fade', 'decay', 'animation'] },
    { key: 'cursor_trail_start_threshold', label: 'Trail Start Threshold',     description: 'Minimum cell jump distance required to trigger cursor trail animation.', tags: ['trail', 'threshold', 'jump', 'animation'] },
  ]),

  ...items('scrollback', 'Scrollback', [
    { key: 'scrollback_lines',             label: 'Scrollback Lines',            description: 'Number of lines kept in the scrollback buffer. 0 for unlimited.',      tags: ['history', 'buffer', 'lines', 'memory'] },
    { key: 'scrollback_pager',             label: 'Scrollback Pager',            description: 'Command used to view scrollback content in a pager like less or bat.',  tags: ['pager', 'less', 'bat', 'view history'] },
    { key: 'scrollback_pager_history_size', label: 'Pager History Size',         description: 'Maximum size in MB of the scrollback pager history file.',              tags: ['pager', 'history size', 'disk', 'file'] },
    { key: 'wheel_scroll_multiplier',      label: 'Scroll Speed',                description: 'Lines to scroll per mouse wheel notch. Higher values scroll faster.',  tags: ['mouse wheel', 'scroll speed', 'multiplier', 'sensitivity'] },
    { key: 'wheel_scroll_min_lines',       label: 'Minimum Scroll Lines',        description: 'Minimum number of lines scrolled per wheel event, regardless of speed.', tags: ['wheel', 'scroll minimum', 'mouse'] },
    { key: 'touch_scroll_multiplier',      label: 'Touch Scroll Multiplier',     description: 'Lines per unit of touchpad scroll gesture.',                            tags: ['touchpad', 'trackpad', 'scroll', 'gesture'] },
  ]),

  ...items('mouse', 'Mouse', [
    { key: 'mouse_hide_wait',        label: 'Hide Mouse Pointer After',  description: 'Seconds of inactivity before the mouse pointer is hidden. 0 to never hide.', tags: ['mouse hide', 'auto hide', 'cursor hide', 'pointer'] },
    { key: 'url_color',              label: 'URL Highlight Color',        description: 'Color used to underline detected URLs in the terminal output.',               tags: ['link color', 'hyperlink', 'url underline'] },
    { key: 'url_style',              label: 'URL Underline Style',        description: 'Style of underline used under detected URLs: curly, straight, double, etc.',  tags: ['link style', 'hyperlink', 'underline', 'url'] },
    { key: 'open_url_with',          label: 'Open URL With',              description: 'Application used to open clicked URLs. "default" uses the system browser.',   tags: ['browser', 'url handler', 'xdg-open', 'open link'] },
    { key: 'url_prefixes',           label: 'URL Prefixes',               description: 'URL schemes that Kitty will detect and make clickable in the terminal.',      tags: ['http', 'https', 'ftp', 'link detection', 'scheme'] },
    { key: 'copy_on_select',         label: 'Copy on Select',             description: 'Automatically copy selected text to clipboard or primary selection.',         tags: ['clipboard', 'auto copy', 'selection', 'primary'] },
    { key: 'paste_actions',          label: 'Paste Actions',              description: 'Actions taken before pasting: sanitize bracketed paste, confirm large pastes.', tags: ['paste', 'clipboard', 'sanitize', 'bracket'] },
    { key: 'url_excluded_characters', label: 'URL Excluded Characters',   description: 'Characters to exclude from URL detection when parsing terminal output.', tags: ['url', 'link', 'exclude', 'characters', 'detection'] },
    { key: 'clear_selection_on_clipboard_loss', label: 'Clear Selection on Clipboard Loss', description: 'Clear visual selection when clipboard content changes (Linux primary selection).', tags: ['selection', 'clipboard', 'clear', 'primary', 'linux'] },
    { key: 'select_by_word_chars',   label: 'Word Selection Characters',  description: 'Characters treated as word boundaries when double-clicking to select.',      tags: ['double click', 'word select', 'boundary', 'delimiter'] },
  ]),

  ...items('performance', 'Performance', [
    { key: 'repaint_delay',      label: 'Repaint Delay',        description: 'Minimum delay in ms between repaints. Lower = smoother, higher = more efficient.', tags: ['fps', 'refresh rate', 'repaint', 'render'] },
    { key: 'input_delay',        label: 'Input Delay',          description: 'Delay in ms to wait for more input before drawing. Batches keystrokes..',         tags: ['latency', 'input lag', 'keystroke', 'batch'] },
    { key: 'sync_to_monitor',    label: 'Sync to Monitor',      description: 'Synchronize repaints to the monitor refresh rate (vsync). Reduces tearing.',     tags: ['vsync', 'tearing', 'monitor sync', 'refresh'] },
    { key: 'enable_audio_bell',  label: 'Audio Bell',           description: 'Play an audible bell sound on BEL character. Disable for silent operation.',      tags: ['beep', 'bell sound', 'audio', 'system bell'] },
  ]),

  ...items('bell', 'Bell', [
    { key: 'enable_audio_bell',      label: 'Audio Bell',          description: 'Enable or disable the audible bell sound for BEL characters.',                 tags: ['beep', 'audio', 'sound', 'alert'] },
    { key: 'visual_bell_duration',   label: 'Visual Bell Duration', description: 'Duration in seconds to flash the window on bell. 0 to disable visual bell.',  tags: ['flash', 'visual', 'bell flash', 'screen flash'] },
    { key: 'visual_bell_color',      label: 'Visual Bell Color',    description: 'Color used for the window flash when the visual bell triggers.',               tags: ['flash color', 'bell color', 'visual', 'background'] },
    { key: 'window_alert_on_bell',   label: 'Window Alert on Bell', description: 'Request attention from the window manager (taskbar flash) on bell.',          tags: ['taskbar', 'alert', 'notification', 'wm'] },
    { key: 'bell_on_tab',            label: 'Bell on Tab',          description: 'Show a bell indicator on the tab that triggered the bell.',                    tags: ['tab bell', 'tab indicator', 'alert', 'notification'] },
    { key: 'command_on_bell',        label: 'Command on Bell',      description: 'Run a shell command when a bell is triggered.',                                tags: ['bell hook', 'command', 'trigger', 'script'] },
  ]),

  ...items('window_layout', 'Window & Layout', [
    { key: 'remember_window_size',    label: 'Remember Window Size',   description: 'Restore the previous window size on launch instead of using initial size.',  tags: ['window size', 'persistent', 'restore', 'startup'] },
    { key: 'initial_window_width',    label: 'Initial Window Width',   description: 'Width of the terminal window when first opened.',                            tags: ['width', 'startup size', 'columns', 'window'] },
    { key: 'initial_window_height',   label: 'Initial Window Height',  description: 'Height of the terminal window when first opened.',                           tags: ['height', 'startup size', 'rows', 'window'] },
    { key: 'window_border_width',     label: 'Window Border Width',    description: 'Thickness of the border drawn around each split terminal pane.',             tags: ['border', 'split', 'pane', 'divider', 'thickness'] },
    { key: 'window_margin_width',     label: 'Window Margin Width',    description: 'Space outside the terminal content area, between content and window edge.',  tags: ['margin', 'padding', 'space', 'outer', 'gap'] },
    { key: 'window_padding_width',    label: 'Window Padding',         description: 'Inner padding between the terminal text and the window border.',             tags: ['padding', 'margin', 'space', 'inner', 'gap'] },
    { key: 'active_border_color',     label: 'Active Border Color',    description: 'Color of the border around the currently focused terminal split.',           tags: ['active', 'focused', 'border color', 'pane', 'highlight'] },
    { key: 'inactive_border_color',   label: 'Inactive Border Color',  description: 'Color of the border around unfocused terminal splits.',                      tags: ['inactive', 'unfocused', 'border color', 'pane'] },
    { key: 'bell_border_color',       label: 'Bell Border Color',      description: 'Color of the split border when a bell fires in that pane.',                  tags: ['bell', 'alert', 'border color', 'pane'] },
    { key: 'inactive_text_alpha',     label: 'Inactive Text Alpha',    description: 'Opacity multiplier for text in unfocused terminal splits.',                  tags: ['inactive', 'dim', 'alpha', 'opacity', 'pane'] },
    { key: 'hide_window_decorations', label: 'Hide Window Decorations', description: 'Remove the OS title bar and window chrome for a clean, minimal look.',     tags: ['titlebar', 'decorations', 'chromeless', 'borderless', 'minimal'] },
    { key: 'resize_debounce_time',    label: 'Resize Debounce',        description: 'Delay before redrawing after a resize to prevent excessive redraws.',        tags: ['resize', 'debounce', 'performance', 'redraw'] },
    { key: 'draw_minimal_borders',    label: 'Minimal Borders',        description: 'Draw slimmer borders by omitting redundant edges between adjacent panes.',   tags: ['border', 'minimal', 'thin', 'pane', 'split'] },
    { key: 'placement_strategy',      label: 'Placement Strategy',     description: 'How content is placed inside the window: center or top-left aligned.',      tags: ['centering', 'alignment', 'content', 'placement'] },
  ]),

  ...items('tab_bar', 'Tab Bar', [
    { key: 'tab_bar_edge',         label: 'Tab Bar Position',       description: 'Where the tab bar appears: top or bottom of the window.',                     tags: ['tabs', 'position', 'top', 'bottom'] },
    { key: 'tab_bar_margin_width', label: 'Tab Bar Margin',         description: 'Horizontal margin in points on either side of the tab bar.',                 tags: ['tabs', 'margin', 'spacing', 'gap'] },
    { key: 'tab_bar_style',        label: 'Tab Bar Style',          description: 'Visual style of the tab bar: fade, slant, separator, powerline, hidden.',    tags: ['tabs', 'style', 'powerline', 'slant', 'separator', 'fade'] },
    { key: 'tab_bar_align',        label: 'Tab Bar Alignment',      description: 'Horizontal alignment of tabs within the tab bar: left, center, or right.',   tags: ['tabs', 'align', 'center', 'left', 'right'] },
    { key: 'tab_min_tabs',         label: 'Minimum Tabs to Show',   description: 'Minimum number of open tabs needed before the tab bar is displayed.',        tags: ['tabs', 'hide single', 'minimum', 'show'] },
    { key: 'tab_switch_strategy',  label: 'Tab Switch Strategy',    description: 'Which tab to focus when the active tab is closed: previous, last, right.',   tags: ['tabs', 'close', 'switch', 'focus'] },
    { key: 'tab_fade',             label: 'Tab Fade Colors',        description: 'Number of cells used to fade the tab bar background into the terminal.',     tags: ['tabs', 'fade', 'gradient', 'blend'] },
    { key: 'tab_separator',        label: 'Tab Separator',          description: 'Character used between tabs when using the separator bar style.',             tags: ['tabs', 'separator', 'divider', 'character'] },
    { key: 'tab_title_template',   label: 'Tab Title Template',     description: 'Python template string for the tab label. Supports variables like title.',   tags: ['tabs', 'title', 'label', 'template', 'format'] },
    { key: 'active_tab_foreground', label: 'Active Tab Foreground', description: 'Text color of the currently active tab.',                                    tags: ['tabs', 'active', 'color', 'foreground', 'text'] },
    { key: 'active_tab_background', label: 'Active Tab Background', description: 'Background color of the currently active tab.',                              tags: ['tabs', 'active', 'color', 'background'] },
    { key: 'active_tab_font_style', label: 'Active Tab Font Style', description: 'Font style of the active tab text: bold, italic, bold-italic, or normal.',   tags: ['tabs', 'active', 'bold', 'font', 'style'] },
    { key: 'inactive_tab_foreground', label: 'Inactive Tab Foreground', description: 'Text color of inactive (unfocused) tabs.',                               tags: ['tabs', 'inactive', 'color', 'foreground'] },
    { key: 'inactive_tab_background', label: 'Inactive Tab Background', description: 'Background color of inactive tabs.',                                    tags: ['tabs', 'inactive', 'color', 'background'] },
  ]),

  ...items('colors', 'Colors', [
    { key: 'foreground',            label: 'Foreground Color',        description: 'Default text color for the terminal output.',                                 tags: ['text color', 'fg', 'default color', 'font color'] },
    { key: 'background',            label: 'Background Color',        description: 'Default background color of the terminal window.',                            tags: ['bg', 'background', 'window color', 'canvas'] },
    { key: 'background_opacity',    label: 'Background Opacity',      description: 'Transparency of the terminal background. Requires a compositor to work.',    tags: ['opacity', 'transparency', 'alpha', 'blur', 'translucent'] },
    { key: 'background_blur',       label: 'Background Blur',         description: 'Blur radius for the transparent background. Requires opacity < 1.',          tags: ['blur', 'frosted glass', 'gaussian', 'opacity'] },
    { key: 'background_tint',       label: 'Background Tint',         description: 'Percentage of the foreground color blended into the background.',            tags: ['tint', 'blend', 'colorize', 'overlay'] },
    { key: 'dim_opacity',           label: 'Dim Opacity',             description: 'Opacity applied to dimmed text (e.g., inactive pane text).',                 tags: ['dim', 'faded', 'opacity', 'inactive'] },
    { key: 'selection_foreground',  label: 'Selection Foreground',    description: 'Text color of selected text. Leave empty to use the reverse of the cell.',   tags: ['selection', 'highlight', 'foreground', 'text'] },
    { key: 'selection_background',  label: 'Selection Background',    description: 'Background color of selected text.',                                         tags: ['selection', 'highlight', 'background', 'mark'] },
    { key: 'color0',                label: 'ANSI Color 0 - Black',    description: 'ANSI color index 0. The standard terminal black.',                           tags: ['ansi', 'black', 'color0', 'palette'] },
    { key: 'color1',                label: 'ANSI Color 1 - Red',      description: 'ANSI color index 1. The standard terminal red.',                             tags: ['ansi', 'red', 'color1', 'error', 'palette'] },
    { key: 'color2',                label: 'ANSI Color 2 - Green',    description: 'ANSI color index 2. The standard terminal green.',                           tags: ['ansi', 'green', 'color2', 'success', 'palette'] },
    { key: 'color3',                label: 'ANSI Color 3 - Yellow',   description: 'ANSI color index 3. The standard terminal yellow.',                          tags: ['ansi', 'yellow', 'color3', 'warning', 'palette'] },
    { key: 'color4',                label: 'ANSI Color 4 - Blue',     description: 'ANSI color index 4. The standard terminal blue.',                            tags: ['ansi', 'blue', 'color4', 'palette'] },
    { key: 'color5',                label: 'ANSI Color 5 - Magenta',  description: 'ANSI color index 5. The standard terminal magenta or purple.',               tags: ['ansi', 'magenta', 'color5', 'purple', 'palette'] },
    { key: 'color6',                label: 'ANSI Color 6 - Cyan',     description: 'ANSI color index 6. The standard terminal cyan.',                            tags: ['ansi', 'cyan', 'color6', 'teal', 'palette'] },
    { key: 'color7',                label: 'ANSI Color 7 - White',    description: 'ANSI color index 7. The standard terminal white (light gray).',              tags: ['ansi', 'white', 'color7', 'light', 'palette'] },
    { key: 'color8',                label: 'ANSI Color 8 - Br.Black', description: 'ANSI color index 8. Bright black / dark gray.',                             tags: ['ansi', 'bright black', 'dark gray', 'color8', 'palette'] },
    { key: 'color9',                label: 'ANSI Color 9 - Br.Red',   description: 'ANSI color index 9. Bright red.',                                            tags: ['ansi', 'bright red', 'color9', 'palette'] },
    { key: 'color10',               label: 'ANSI Color 10 - Br.Green', description: 'ANSI color index 10. Bright green.',                                       tags: ['ansi', 'bright green', 'color10', 'palette'] },
    { key: 'color11',               label: 'ANSI Color 11 - Br.Yellow', description: 'ANSI color index 11. Bright yellow.',                                     tags: ['ansi', 'bright yellow', 'color11', 'palette'] },
    { key: 'color12',               label: 'ANSI Color 12 - Br.Blue', description: 'ANSI color index 12. Bright blue.',                                         tags: ['ansi', 'bright blue', 'color12', 'palette'] },
    { key: 'color13',               label: 'ANSI Color 13 - Br.Magenta', description: 'ANSI color index 13. Bright magenta.',                                   tags: ['ansi', 'bright magenta', 'color13', 'palette'] },
    { key: 'color14',               label: 'ANSI Color 14 - Br.Cyan', description: 'ANSI color index 14. Bright cyan.',                                         tags: ['ansi', 'bright cyan', 'color14', 'palette'] },
    { key: 'color15',               label: 'ANSI Color 15 - Br.White', description: 'ANSI color index 15. Bright white.',                                       tags: ['ansi', 'bright white', 'color15', 'palette'] },
    { key: 'mark1_foreground',      label: 'Mark 1 Foreground',       description: 'Text color of the first regex mark group.',                                  tags: ['mark', 'regex', 'highlight', 'match'] },
    { key: 'mark1_background',      label: 'Mark 1 Background',       description: 'Background color of the first regex mark group.',                            tags: ['mark', 'regex', 'highlight', 'match'] },
    { key: 'mark2_foreground',      label: 'Mark 2 Foreground',       description: 'Text color of the second regex mark group.',                                 tags: ['mark', 'regex', 'highlight', 'match'] },
    { key: 'mark2_background',      label: 'Mark 2 Background',       description: 'Background color of the second regex mark group.',                           tags: ['mark', 'regex', 'highlight', 'match'] },
    { key: 'mark3_foreground',      label: 'Mark 3 Foreground',       description: 'Text color of the third regex mark group.',                                  tags: ['mark', 'regex', 'highlight', 'match'] },
    { key: 'mark3_background',      label: 'Mark 3 Background',       description: 'Background color of the third regex mark group.',                            tags: ['mark', 'regex', 'highlight', 'match'] },
    { key: 'dynamic_background_opacity', label: 'Dynamic Background Opacity', description: 'Allow changing background opacity at runtime with keyboard shortcuts.',   tags: ['opacity', 'dynamic', 'transparency', 'adjust', 'runtime'] },
  ]),

  ...items('advanced', 'Advanced', [
    { key: 'shell',                   label: 'Shell',                     description: 'Shell executable to launch. "." means use the system default shell.',     tags: ['bash', 'zsh', 'fish', 'shell', 'executable'] },
    { key: 'editor',                  label: 'Editor',                    description: 'Text editor for editing config or viewing scrollback. "." uses $EDITOR.',  tags: ['vim', 'neovim', 'nano', 'editor', 'EDITOR'] },
    { key: 'close_on_child_death',    label: 'Close on Child Death',      description: 'Close the window automatically when the shell process exits.',             tags: ['exit', 'close', 'shell death', 'auto close'] },
    { key: 'allow_remote_control',    label: 'Allow Remote Control',      description: 'Allow external programs to control Kitty via the remote control protocol.', tags: ['remote', 'kitty remote', 'IPC', 'control', 'API'] },
    { key: 'listen_on',               label: 'Listen On',                 description: 'Socket path or address for the remote control API to listen on.',          tags: ['socket', 'unix', 'listen', 'IPC', 'remote'] },
    { key: 'update_check_interval',   label: 'Update Check Interval',     description: 'Hours between update checks. 0 to disable automatic update checks.',      tags: ['update', 'auto update', 'check', 'version'] },
    { key: 'startup_session',         label: 'Startup Session',           description: 'Path to a session file that describes windows/tabs to open on launch.',    tags: ['session', 'startup', 'layout', 'restore', 'launch'] },
    { key: 'clipboard_control',       label: 'Clipboard Control',         description: 'Which clipboard access operations to allow from terminal programs.',       tags: ['clipboard', 'copy', 'paste', 'OSC 52', 'security'] },
    { key: 'clipboard_max_size',      label: 'Clipboard Max Size',        description: 'Maximum clipboard size in MB that Kitty will handle.',                     tags: ['clipboard', 'size limit', 'memory', 'buffer'] },
    { key: 'shell_integration',       label: 'Shell Integration',         description: 'Enable shell integration features like prompt marks and SSH kitten.',      tags: ['shell integration', 'prompt', 'marks', 'SSH', 'kitten'] },
    { key: 'term',                    label: 'Terminal Type ($TERM)',      description: 'Value of the $TERM environment variable. Defaults to xterm-kitty.',        tags: ['$TERM', 'TERM', 'terminfo', 'environment', 'xterm'] },
    { key: 'env',                     label: 'Environment Variables',     description: 'Extra environment variables to set in all shell processes.',               tags: ['env', 'environment', 'variable', 'PATH', 'export'] },
    { key: 'watcher',                 label: 'Watcher',                   description: 'Python script path that receives window lifecycle events from Kitty.',    tags: ['watcher', 'hook', 'plugin', 'python', 'script', 'event'] },
  ]),

  ...items('os_specific', 'OS Specific', [
    { key: 'wayland_titlebar_color',         label: 'Wayland Title Bar Color',     description: 'Color of the client-side title bar decoration on Wayland.',         tags: ['wayland', 'titlebar', 'linux', 'decoration', 'csd'] },
    { key: 'linux_display_server',           label: 'Linux Display Server',        description: 'Force Kitty to use X11 or Wayland, or detect automatically.',        tags: ['X11', 'wayland', 'linux', 'display', 'compositor'] },
    { key: 'macos_title_bar_color',          label: 'macOS Title Bar Color',       description: 'Color of the macOS native title bar: system, background, or a hex.', tags: ['macos', 'titlebar', 'apple', 'native', 'decoration'] },
    { key: 'macos_option_as_alt',            label: 'macOS Option as Alt',         description: 'Treat the Option key as Alt for keyboard shortcuts on macOS.',       tags: ['macos', 'option', 'alt', 'meta', 'keyboard', 'modifier'] },
    { key: 'macos_hide_from_tasks',          label: 'Hide from macOS Dock',        description: 'Hide the Kitty window from the macOS Dock and Cmd+Tab switcher.',    tags: ['macos', 'dock', 'hide', 'taskbar', 'app switcher'] },
    { key: 'macos_quit_when_last_window_closes', label: 'Quit When Last Window Closes', description: 'Quit the Kitty app when the last window is closed on macOS.', tags: ['macos', 'quit', 'close', 'window', 'exit'] },
    { key: 'macos_traditional_fullscreen',   label: 'macOS Traditional Fullscreen', description: 'Use legacy non-native fullscreen mode on macOS.',                   tags: ['macos', 'fullscreen', 'legacy', 'native'] },
    { key: 'macos_show_window_title_in',     label: 'Show Title In',               description: 'Where to display the window title on macOS: titlebar, menubar, all.', tags: ['macos', 'title', 'menubar', 'titlebar', 'display'] },
  ]),

];
