export type KittyCursorShape = 'block' | 'beam' | 'underline';
export type KittyCursorShapeUnfocused = 'block' | 'beam' | 'underline' | 'hollow' | 'unchanged';
export type KittyTabBarStyle = 'fade' | 'slant' | 'separator' | 'powerline' | 'custom' | 'hidden';
export type KittyTabBarAlign = 'left' | 'center' | 'right';
export type KittyTabBarEdge = 'top' | 'bottom';
export type KittyTabSwitchStrategy = 'previous' | 'left' | 'right' | 'last';
export type KittyTabPowerlineStyle = 'angled' | 'slanted' | 'round';
export type KittyRemoteControl = 'yes' | 'no' | 'socket-only' | 'socket' | 'password';
export type KittyLigatureControl = 'never' | 'always' | 'cursor';
export type KittyLayout = 'Fat' | 'Grid' | 'Horizontal' | 'Splits' | 'Stack' | 'Tall' | 'Vertical' | '*';
export type KittyUndercurlStyle = 'thin-sparse' | 'thin-dense' | 'thick-sparse' | 'thick-dense';
export type KittyTextCompositionStrategy = 'platform' | 'legacy';
export type KittyMacosOptionAsAlt = 'yes' | 'no' | 'both' | 'left' | 'right';
export type KittyCopyOnSelect = 'yes' | 'no' | 'clipboard';
export type KittyUrlStyle = 'none' | 'straight' | 'double' | 'curly' | 'dotted' | 'dashed';
export type KittyBackgroundImageLayout = 'tiled' | 'mirror-tiled' | 'scaled' | 'clamped' | 'centered' | 'cscaled';
export type KittyPlacementStrategy = 'top-left' | 'top' | 'top-right' | 'left' | 'center' | 'right' | 'bottom-left' | 'bottom' | 'bottom-right';
export type KittyUnderlineHyperlinks = 'hover' | 'always' | 'never';
export type KittyStripTrailingSpaces = 'never' | 'smart' | 'always';
export type KittyMacosColorspace = 'srgb' | 'default' | 'displayp3';
export type KittyHideWindowDecorations = boolean | 'yes' | 'no' | 'titlebar-only' | 'titlebar-and-corners';
export type KittyLinuxDisplayServer = 'x11' | 'wayland' | 'auto';

export interface KittyKeyMap {
  chord: string;
  action: string;
}

export interface KittyMouseMap {
  button: string;
  event: string;
  modes: string;
  action: string;
}

export interface KittyFontsConfig {
  font_family: string;
  bold_font: string;
  italic_font: string;
  bold_italic_font: string;
  font_size: number;
  force_ltr: boolean;
  symbol_map: string[];
  narrow_symbols: string[];
  disable_ligatures: KittyLigatureControl;
  font_features: string[];
  modify_font: string[];
  box_drawing_scale: number[];
  undercurl_style: KittyUndercurlStyle;
  underline_exclusion: number;
  text_composition_strategy: KittyTextCompositionStrategy;
  text_fg_override_threshold: number;
}

export interface KittyCursorConfig {
  cursor: string;
  cursor_text_color: string;
  cursor_shape: KittyCursorShape;
  cursor_shape_unfocused: KittyCursorShapeUnfocused;
  cursor_beam_thickness: number;
  cursor_underline_thickness: number;
  cursor_blink_interval: number;
  cursor_stop_blinking_after: number;
  cursor_trail: number;
  cursor_trail_color: string;
  cursor_trail_decay: number[];
  cursor_trail_start_threshold: number;
  // Alive effects - config driven
  cursor_glow_enabled: boolean;
  cursor_glow_color: string;
  cursor_glow_intensity: number;
  cursor_glow_radius: number;
  cursor_breathing_enabled: boolean;
  cursor_breathing_speed: number;
  cursor_breathing_min_opacity: number;
  cursor_breathing_max_opacity: number;
  // Additional alive effects
  typing_simulation_enabled: boolean;
  typing_simulation_speed: number;
  active_line_pulse_enabled: boolean;
  active_line_pulse_intensity: number;
  idle_animation_enabled: boolean;
  idle_animation_speed: number;
}

export interface KittyScrollbackConfig {
  scrollback_lines: number;
  scrollback_pager: string;
  scrollback_pager_history_size: number;
  scrollback_fill_enlarged_window: boolean;
  wheel_scroll_multiplier: number;
  wheel_scroll_min_lines: number;
  touch_scroll_multiplier: number;
  pixel_scroll: boolean;
  momentum_scroll: boolean;
  scrollbar: string;
}

export interface KittyMouseConfig {
  mouse_hide_wait: number;
  url_color: string;
  url_style: KittyUrlStyle;
  open_url_with: string;
  url_prefixes: string[];
  detect_urls: boolean;
  show_hyperlink_targets: boolean;
  underline_hyperlinks: KittyUnderlineHyperlinks;
  copy_on_select: KittyCopyOnSelect;
  paste_actions: string[];
  strip_trailing_spaces: KittyStripTrailingSpaces;
  select_by_word_characters: string;
  select_by_word_characters_forward: string;
  click_interval: number;
  focus_follows_mouse: boolean;
  pointer_shape_when_grabbed: string;
  default_pointer_shape: string;
  pointer_shape_when_dragging: string;
  url_excluded_characters: string;
  clear_selection_on_clipboard_loss: boolean;
}

export interface KittyPerformanceConfig {
  repaint_delay: number;
  input_delay: number;
  sync_to_monitor: boolean;
}

export interface KittyBellConfig {
  enable_audio_bell: boolean;
  visual_bell_duration: number;
  visual_bell_color: string;
  window_alert_on_bell: boolean;
  bell_on_tab: string;
  command_on_bell: string;
  bell_path: string;
  linux_bell_theme: string;
}

export interface KittyWindowLayoutConfig {
  remember_window_size: boolean;
  remember_window_position: boolean;
  initial_window_width: number;
  initial_window_height: number;
  enabled_layouts: KittyLayout[];
  window_resize_step_cells: number;
  window_resize_step_lines: number;
  window_border_width: string;
  draw_minimal_borders: boolean;
  draw_window_borders_for_single_window: boolean;
  window_margin_width: number;
  single_window_margin_width: number;
  window_padding_width: number;
  single_window_padding_width: number;
  placement_strategy: KittyPlacementStrategy;
  active_border_color: string;
  inactive_border_color: string;
  bell_border_color: string;
  inactive_text_alpha: number;
  hide_window_decorations: KittyHideWindowDecorations;
  window_logo_path: string;
  window_logo_position: KittyPlacementStrategy;
  window_logo_alpha: number;
  window_logo_scale: number;
  resize_debounce_time: number;
  resize_in_steps: boolean;
  visual_window_select_characters: string;
  confirm_os_window_close: number;
  confirm_os_window_close_count_background: boolean;
  startup_window: string;
  window_drag_tolerance: number;
  title_bar_padding_x: number;
  title_bar_padding_y: number;
  traffic_light_size: number;
  traffic_light_opacity: number;
  traffic_light_animation_duration: number;
  traffic_light_animation_scale: number;
  window_border_radius: string;
}

export interface KittyTabBarConfig {
  tab_bar_edge: KittyTabBarEdge;
  tab_bar_margin_width: number;
  tab_bar_margin_height: number[];
  tab_bar_style: KittyTabBarStyle;
  tab_bar_align: KittyTabBarAlign;
  tab_bar_min_tabs: number;
  tab_switch_strategy: KittyTabSwitchStrategy;
  tab_fade: number[];
  tab_separator: string;
  tab_powerline_style: KittyTabPowerlineStyle;
  tab_activity_symbol: string;
  tab_title_max_length: number;
  tab_title_template: string;
  active_tab_title_template: string;
  active_tab_foreground: string;
  active_tab_background: string;
  active_tab_font_style: string;
  inactive_tab_foreground: string;
  inactive_tab_background: string;
  inactive_tab_font_style: string;
  tab_bar_background: string;
  tab_bar_margin_color: string;
  tab_bar_hide_path: string;
  tab_bar_drag_threshold: number;
  tab_bar_border_opacity: number;
  tab_padding_horizontal: number;
  tab_padding_vertical: number;
  tab_separator_opacity: number;
}

export interface KittyColorConfig {
  foreground: string;
  background: string;
  background_opacity: number;
  background_blur: number;
  background_image: string;
  background_image_layout: KittyBackgroundImageLayout;
  background_image_linear: boolean;
  background_tint: number;
  background_tint_gaps: number;
  dim_opacity: number;
  selection_foreground: string;
  selection_background: string;
  color0: string;
  color1: string;
  color2: string;
  color3: string;
  color4: string;
  color5: string;
  color6: string;
  color7: string;
  color8: string;
  color9: string;
  color10: string;
  color11: string;
  color12: string;
  color13: string;
  color14: string;
  color15: string;
  color16?: string;
  color17?: string;
  color18?: string;
  color19?: string;
  color20?: string;
  color21?: string;
  color22?: string;
  color23?: string;
  color24?: string;
  color25?: string;
  color26?: string;
  color27?: string;
  color28?: string;
  color29?: string;
  color30?: string;
  color31?: string;
  color32?: string;
  color33?: string;
  color34?: string;
  color35?: string;
  color36?: string;
  color37?: string;
  color38?: string;
  color39?: string;
  color40?: string;
  color41?: string;
  color42?: string;
  color43?: string;
  color44?: string;
  color45?: string;
  color46?: string;
  color47?: string;
  color48?: string;
  color49?: string;
  color50?: string;
  color51?: string;
  color52?: string;
  color53?: string;
  color54?: string;
  color55?: string;
  color56?: string;
  color57?: string;
  color58?: string;
  color59?: string;
  color60?: string;
  color61?: string;
  color62?: string;
  color63?: string;
  color64?: string;
  color65?: string;
  color66?: string;
  color67?: string;
  color68?: string;
  color69?: string;
  color70?: string;
  color71?: string;
  color72?: string;
  color73?: string;
  color74?: string;
  color75?: string;
  color76?: string;
  color77?: string;
  color78?: string;
  color79?: string;
  color80?: string;
  color81?: string;
  color82?: string;
  color83?: string;
  color84?: string;
  color85?: string;
  color86?: string;
  color87?: string;
  color88?: string;
  color89?: string;
  color90?: string;
  color91?: string;
  color92?: string;
  color93?: string;
  color94?: string;
  color95?: string;
  color96?: string;
  color97?: string;
  color98?: string;
  color99?: string;
  color100?: string;
  color101?: string;
  color102?: string;
  color103?: string;
  color104?: string;
  color105?: string;
  color106?: string;
  color107?: string;
  color108?: string;
  color109?: string;
  color110?: string;
  color111?: string;
  color112?: string;
  color113?: string;
  color114?: string;
  color115?: string;
  color116?: string;
  color117?: string;
  color118?: string;
  color119?: string;
  color120?: string;
  color121?: string;
  color122?: string;
  color123?: string;
  color124?: string;
  color125?: string;
  color126?: string;
  color127?: string;
  color128?: string;
  color129?: string;
  color130?: string;
  color131?: string;
  color132?: string;
  color133?: string;
  color134?: string;
  color135?: string;
  color136?: string;
  color137?: string;
  color138?: string;
  color139?: string;
  color140?: string;
  color141?: string;
  color142?: string;
  color143?: string;
  color144?: string;
  color145?: string;
  color146?: string;
  color147?: string;
  color148?: string;
  color149?: string;
  color150?: string;
  color151?: string;
  color152?: string;
  color153?: string;
  color154?: string;
  color155?: string;
  color156?: string;
  color157?: string;
  color158?: string;
  color159?: string;
  color160?: string;
  color161?: string;
  color162?: string;
  color163?: string;
  color164?: string;
  color165?: string;
  color166?: string;
  color167?: string;
  color168?: string;
  color169?: string;
  color170?: string;
  color171?: string;
  color172?: string;
  color173?: string;
  color174?: string;
  color175?: string;
  color176?: string;
  color177?: string;
  color178?: string;
  color179?: string;
  color180?: string;
  color181?: string;
  color182?: string;
  color183?: string;
  color184?: string;
  color185?: string;
  color186?: string;
  color187?: string;
  color188?: string;
  color189?: string;
  color190?: string;
  color191?: string;
  color192?: string;
  color193?: string;
  color194?: string;
  color195?: string;
  color196?: string;
  color197?: string;
  color198?: string;
  color199?: string;
  color200?: string;
  color201?: string;
  color202?: string;
  color203?: string;
  color204?: string;
  color205?: string;
  color206?: string;
  color207?: string;
  color208?: string;
  color209?: string;
  color210?: string;
  color211?: string;
  color212?: string;
  color213?: string;
  color214?: string;
  color215?: string;
  color216?: string;
  color217?: string;
  color218?: string;
  color219?: string;
  color220?: string;
  color221?: string;
  color222?: string;
  color223?: string;
  color224?: string;
  color225?: string;
  color226?: string;
  color227?: string;
  color228?: string;
  color229?: string;
  color230?: string;
  color231?: string;
  color232?: string;
  color233?: string;
  color234?: string;
  color235?: string;
  color236?: string;
  color237?: string;
  color238?: string;
  color239?: string;
  color240?: string;
  color241?: string;
  color242?: string;
  color243?: string;
  color244?: string;
  color245?: string;
  color246?: string;
  color247?: string;
  color248?: string;
  color249?: string;
  color250?: string;
  color251?: string;
  color252?: string;
  color253?: string;
  color254?: string;
  color255?: string;
  mark1_foreground: string;
  mark1_background: string;
  mark2_foreground: string;
  mark2_background: string;
  mark3_foreground: string;
  mark3_background: string;
  dynamic_background_opacity: boolean;
  transparent_background_colors: string[];
}

export interface KittyAdvancedConfig {
  shell: string;
  editor: string;
  close_on_child_death: boolean;
  allow_remote_control: KittyRemoteControl;
  remote_control_password: string[];
  listen_on: string;
  env: Record<string, string>;
  env_read_from_shell: boolean;
  watcher: string[];
  exe_search_path: string[];
  update_check_interval: number;
  startup_session: string;
  clipboard_control: string[];
  clipboard_max_size: number;
  map_timeout: number;
  file_transfer_confirmation_bypass: string[];
  filter_notification: string;
  allow_hyperlinks: string;
  shell_integration: string;
  allow_cloning: string;
  clone_source_strategies: string[];
  term: string;
  forward_stdio: boolean;
  menu_map: string[];
  action_alias: string[];
}

export interface KittyOSSpecificConfig {
  wayland_titlebar_color: string;
  wayland_enable_ime: boolean;
  macos_titlebar_color: string;
  macos_option_as_alt: KittyMacosOptionAsAlt;
  macos_hide_from_tasks: boolean;
  macos_quit_when_last_window_closed: boolean;
  macos_window_resizable: boolean;
  macos_thicken_font: number;
  macos_traditional_fullscreen: boolean;
  macos_show_window_title_in: string;
  macos_menubar_title_max_length: number;
  macos_custom_beam_cursor: boolean;
  macos_colorspace: KittyMacosColorspace;
  macos_dock_badge_on_bell: boolean;
  linux_display_server: KittyLinuxDisplayServer;
}

export interface KittyConfigAST {
  fonts: KittyFontsConfig;
  cursor: KittyCursorConfig;
  scrollback: KittyScrollbackConfig;
  mouse: KittyMouseConfig;
  performance: KittyPerformanceConfig;
  bell: KittyBellConfig;
  window_layout: KittyWindowLayoutConfig;
  tab_bar: KittyTabBarConfig;
  colors: KittyColorConfig;
  advanced: KittyAdvancedConfig;
  os_specific: KittyOSSpecificConfig;
  keyboard_shortcuts: KittyKeyMap[];
  mouse_mappings: KittyMouseMap[];
  unrecognized_directives: string[];
  kitty_mod: string;
}
