import { KittyConfigAST } from './kitty-types';

export const DEFAULT_KITTY_CONFIG: KittyConfigAST = {
  fonts: {
    font_family: 'monospace',
    bold_font: 'auto',
    italic_font: 'auto',
    bold_italic_font: 'auto',
    font_size: 11,
    force_ltr: false,
    symbol_map: [],
    narrow_symbols: [],
    disable_ligatures: 'never',
    font_features: [],
    modify_font: [],
    box_drawing_scale: [0.001, 1, 1.5, 2],
    undercurl_style: 'thin-sparse',
    underline_exclusion: 1,
    text_composition_strategy: 'platform',
    text_fg_override_threshold: 0,
  },
  cursor: {
    cursor: '#cccccc',
    cursor_text_color: '#111111',
    cursor_shape: 'block',
    cursor_shape_unfocused: 'hollow',
    cursor_beam_thickness: 1.5,
    cursor_underline_thickness: 2,
    cursor_blink_interval: -1,
    cursor_stop_blinking_after: 15,
    cursor_trail: 0,
    cursor_trail_color: 'none',
    cursor_trail_decay: [0.1, 0.4],
    cursor_trail_start_threshold: 2,
    // Alive effects - make terminal feel alive
    cursor_glow_enabled: true,
    cursor_glow_color: 'auto',
    cursor_glow_intensity: 0.6,
    cursor_glow_radius: 8,
    cursor_breathing_enabled: true,
    cursor_breathing_speed: 3,
    cursor_breathing_min_opacity: 0.7,
    cursor_breathing_max_opacity: 1.0,
    // Additional alive effects
    typing_simulation_enabled: true,
    typing_simulation_speed: 50,
    active_line_pulse_enabled: true,
    active_line_pulse_intensity: 0.15,
    idle_animation_enabled: true,
    idle_animation_speed: 8,
  },
  scrollback: {
    scrollback_lines: 2000,
    scrollback_pager: 'less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER',
    scrollback_pager_history_size: 0,
    scrollback_fill_enlarged_window: false,
    wheel_scroll_multiplier: 5,
    wheel_scroll_min_lines: 1,
    touch_scroll_multiplier: 1,
    pixel_scroll: false,
    momentum_scroll: false,
    scrollbar: '',
  },
  mouse: {
    mouse_hide_wait: 3,
    url_color: '#0087bd',
    url_style: 'curly',
    open_url_with: 'default',
    url_prefixes: ['http', 'https', 'file', 'ftp', 'gemini', 'irc', 'mailto'],
    detect_urls: true,
    show_hyperlink_targets: false,
    underline_hyperlinks: 'hover',
    copy_on_select: 'no',
    paste_actions: ['quote-urls-at-prompt'],
    strip_trailing_spaces: 'smart',
    select_by_word_characters: '@-./_~?&=%+#',
    select_by_word_characters_forward: '',
    click_interval: -1,
    focus_follows_mouse: false,
    pointer_shape_when_grabbed: 'arrow',
    default_pointer_shape: 'beam',
    pointer_shape_when_dragging: 'beam',
    url_excluded_characters: '',
    clear_selection_on_clipboard_loss: false,
  },
  performance: {
    repaint_delay: 10,
    input_delay: 3,
    sync_to_monitor: true,
  },
  bell: {
    enable_audio_bell: true,
    visual_bell_duration: 0,
    visual_bell_color: 'none',
    window_alert_on_bell: true,
    bell_on_tab: '🔔 ',
    command_on_bell: 'none',
    bell_path: 'none',
    linux_bell_theme: '__custom',
  },
  window_layout: {
    remember_window_size: true,
    remember_window_position: false,
    initial_window_width: 640,
    initial_window_height: 400,
    enabled_layouts: ['*'],
    window_resize_step_cells: 2,
    window_resize_step_lines: 2,
    window_border_width: '0.5pt',
    draw_minimal_borders: true,
    draw_window_borders_for_single_window: false,
    window_margin_width: 0,
    single_window_margin_width: -1,
    window_padding_width: 0,
    single_window_padding_width: -1,
    placement_strategy: 'center',
    active_border_color: '#00ff00',
    inactive_border_color: '#cccccc',
    bell_border_color: '#ff5a00',
    inactive_text_alpha: 1,
    hide_window_decorations: false,
    window_logo_path: 'none',
    window_logo_position: 'bottom-right',
    window_logo_alpha: 0.5,
    window_logo_scale: 0,
    resize_debounce_time: 0.1,
    resize_in_steps: false,
    visual_window_select_characters: '1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    confirm_os_window_close: -1,
    confirm_os_window_close_count_background: false,
    startup_window: 'normal',
    window_drag_tolerance: 0,
    title_bar_padding_x: 16,
    title_bar_padding_y: 10,
    traffic_light_size: 12,
    traffic_light_opacity: 0.8,
    traffic_light_animation_duration: 0.3,
    traffic_light_animation_scale: 1.05,
    window_border_radius: '0.5rem',
  },
  tab_bar: {
    tab_bar_edge: 'bottom',
    tab_bar_margin_width: 0,
    tab_bar_margin_height: [0, 0],
    tab_bar_style: 'fade',
    tab_bar_align: 'left',
    tab_bar_min_tabs: 2,
    tab_switch_strategy: 'previous',
    tab_fade: [0.25, 0.5, 0.75, 1],
    tab_separator: ' ┇',
    tab_powerline_style: 'angled',
    tab_activity_symbol: 'none',
    tab_title_max_length: 0,
    tab_title_template: '{title}',
    active_tab_title_template: 'none',
    active_tab_foreground: '#000',
    active_tab_background: '#eee',
    active_tab_font_style: 'bold-italic',
    inactive_tab_foreground: '#444',
    inactive_tab_background: '#999',
    inactive_tab_font_style: 'normal',
    tab_bar_background: 'none',
    tab_bar_margin_color: 'none',
    tab_bar_hide_path: 'none',
    tab_bar_drag_threshold: 0,
    tab_bar_border_opacity: 0.2,
    tab_padding_horizontal: 16,
    tab_padding_vertical: 8,
    tab_separator_opacity: 0.6,
  },
  colors: {
    foreground: '#dddddd',
    background: '#000000',
    background_opacity: 1,
    background_blur: 0,
    background_image: 'none',
    background_image_layout: 'tiled',
    background_image_linear: false,
    background_tint: 0,
    background_tint_gaps: 1,
    dim_opacity: 0.4,
    selection_foreground: '#000000',
    selection_background: '#fffacd',
    color0: '#000000',
    color1: '#cc0403',
    color2: '#19cb00',
    color3: '#cecb00',
    color4: '#0d73cc',
    color5: '#cb1ed1',
    color6: '#0dcdcd',
    color7: '#dddddd',
    color8: '#767676',
    color9: '#f2201f',
    color10: '#23fd00',
    color11: '#fffd00',
    color12: '#1a8fff',
    color13: '#fd28ff',
    color14: '#14ffff',
    color15: '#ffffff',
    mark1_foreground: 'black',
    mark1_background: '#98d3cb',
    mark2_foreground: 'black',
    mark2_background: '#f2dcd3',
    mark3_foreground: 'black',
    mark3_background: '#f274bc',
    dynamic_background_opacity: false,
    transparent_background_colors: [],
  },
  advanced: {
    shell: '.',
    editor: '.',
    close_on_child_death: false,
    allow_remote_control: 'no',
    remote_control_password: [],
    listen_on: 'none',
    env: {},
    env_read_from_shell: false,
    watcher: [],
    exe_search_path: [],
    update_check_interval: 24,
    startup_session: 'none',
    clipboard_control: ['write-clipboard', 'write-primary', 'read-clipboard-ask', 'read-primary-ask'],
    clipboard_max_size: 512,
    map_timeout: 0,
    file_transfer_confirmation_bypass: [],
    filter_notification: '',
    allow_hyperlinks: 'yes',
    shell_integration: 'enabled',
    allow_cloning: 'ask',
    clone_source_strategies: ['venv', 'conda', 'env_var', 'path'],
    term: 'xterm-kitty',
    forward_stdio: false,
    menu_map: [],
    action_alias: [],
  },
  os_specific: {
    wayland_titlebar_color: 'system',
    wayland_enable_ime: true,
    macos_titlebar_color: 'system',
    macos_option_as_alt: 'no',
    macos_hide_from_tasks: false,
    macos_quit_when_last_window_closed: false,
    macos_window_resizable: true,
    macos_thicken_font: 0,
    macos_traditional_fullscreen: false,
    macos_show_window_title_in: 'all',
    macos_menubar_title_max_length: 0,
    macos_custom_beam_cursor: false,
    macos_colorspace: 'srgb',
    macos_dock_badge_on_bell: false,
    linux_display_server: 'auto',
  },
  keyboard_shortcuts: [],
  mouse_mappings: [],
  unrecognized_directives: [],
  kitty_mod: 'ctrl+shift',
};
